apiVersion: v1
data:
  nginx.conf: |-
    worker_processes 4;
    worker_rlimit_nofile 40000;

    events {
        worker_connections 8192;
    }

    stream {
        server {
            listen     10443;
            proxy_pass 127.0.0.1:6443;

            proxy_ssl  on;
            proxy_ssl_certificate         /etc/kubernetes/ssl/kube-node.pem;
            proxy_ssl_certificate_key     /etc/kubernetes/ssl/kube-node-key.pem;
            proxy_ssl_trusted_certificate /etc/kubernetes/ssl/kube-ca.pem;

            proxy_ssl_session_reuse  on ;

        }
    }
kind: ConfigMap
metadata:
  name: nginx-proxy
  namespace: kube-system

